apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarqube
  labels:
    name: pvsonarqube
spec:
  storageClassName: storage-sonarqube
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-sonarqube"